[tools]
"cargo:stellar-cli" = "23.1.4"

[env]
STELLAR_NETWORK = "mainnet"
STELLAR_SOURCE = "blend-mainnet"
WASM = "target/wasm32-unknown-unknown/optimized/oracle_aggregator.wasm"
ADMIN = "GDH3FRHOOWXYXEASH43N2VOVFOPJSVJF3EQFSLBLJYFPHOUAF4N4AETH"
BASE = '{"Other":"USD"}'
DECIMALS = 14
MAX_AGE = 600
FEE = 5000000
CONTRACT_ID = "CAVRP26CWW6IUEXBRA3Q2T2SHBUVBC2DF43M4E23LEZGW5ZEIB62HALS"